// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $about from "./routes/about.tsx";
import * as $api_categories from "./routes/api/categories.ts";
import * as $blog_index from "./routes/blog/index.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $products from "./routes/products.tsx";
import * as $profile_userID_ from "./routes/profile/[userID].tsx";
import * as $profile_index from "./routes/profile/index.tsx";
import * as $search from "./routes/search.tsx";

import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/about.tsx": $about,
    "./routes/api/categories.ts": $api_categories,
    "./routes/blog/index.tsx": $blog_index,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/products.tsx": $products,
    "./routes/profile/[userID].tsx": $profile_userID_,
    "./routes/profile/index.tsx": $profile_index,
    "./routes/search.tsx": $search,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
